version: '3.7'

services:
  client:
    container_name: fantasy-client
    restart: always
    build:
      context: ./client
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=traefik_public"
    - "traefik.backend=client"
    - "traefik.frontend.rule=Host:fantasy.elvinfeng.com"
    - "traefik.port=8080"
    networks:
    - traefik_public
    - private

networks:
  traefik_public:
    external: true
  private: