version: '3.7'

services:
  fantasy:
    container_name: fantasy-client
    image: elvinfeng/fantasy:client
    restart: always
    build:
      context: ./client
    labels:
    - traefik.enable=true
    - traefik.http.routers.fantasy.rule=Host(`fantasy.elvinfeng.com`)
    - traefik.http.routers.fantasy.tls=true
    - traefik.http.routers.fantasy.tls.certresolver=lets-encrypt
    - traefik.port=80
    networks:
    - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge