version: '3.7'

services:
  flask:
    container_name: flask-server
    image: elvinfeng/flask:server
    restart: always
    build:
      context: .
    environment:
      - HOST=localhost
      - PORT=8080